/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/matcha/matchaTheme.ts
 * Command: astryx theme build src/themes/matcha/matchaTheme.ts
 * Generated: 2026-07-24T12:50:18.923Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const matchaTheme: DefinedTheme;
